version: '3.0'

networks:
  formance:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  application:
    container_name: server
    hostname: server
    image: antithesis-sandbox:antithesis-latest
    command: server
    ports:
      - "8080:8080"
    environment:
      GOMAXPROCS: 2
    networks:
      formance:
        ipv4_address: 10.0.0.16
    
  workload-1:
    container_name: workload-1
    hostname: workload-1
    image: antithesis-sandbox:antithesis-latest
    command: workload
    environment:
      GOMAXPROCS: 2
    depends_on:
      - application
    networks:
      formance:
        ipv4_address: 10.0.0.17

  workload-2:
    container_name: workload-2
    hostname: workload-2
    image: antithesis-sandbox:antithesis-latest
    command: workload
    environment:
      GOMAXPROCS: 2
    depends_on:
      - application
    networks:
      formance:
        ipv4_address: 10.0.0.18